#!/bin/sh /etc/rc.common
# Copyright (C) 2015 brglng@github.com

START=99
STOP=99

start() {
        service_start /root/syncthing-linux-amd64-v1.2.0 2>&1 | logger -t syncthing &
}

stop() {
        service_stop /root/syncthing-linux-amd64-v1.2.0
}
